#   docker network create --driver bridge --subnet=150.50.50.0/24 my-net

services:
  confluence:
    image: atlassian/confluence-server:latest
    restart: always
    container_name: confluence
    hostname: confluence
    environment:
      ATL_DB_DRIVER: 'org.postgresql.Driver'
      ATL_DB_TYPE: 'postgresql'
      ATL_JDBC_URL: 'jdbc:postgresql://host:port/database'
      ATL_JDBC_USER: 'username'
      ATL_JDBC_PASSWORD: 'password'
      ATL_PROXY_NAME: confluence.host.com
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: 'https'
      ATL_TOMCAT_SECURE: 'true'
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m
    volumes:
      - /data/docker/confluence:/var/atlassian/application-data/confluence
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
    networks:
      my-net:
    ports:
      - 8090:8090
      - 8091:8091

networks:
  my-net:
    external: true
