#   docker network create --driver bridge --subnet=150.50.50.0/24 my-net

services:
  gitlab-ce:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.host.com'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.host.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
    ports:
      - 8020:80
      - 8043:443
      - 8022:22
    volumes:
      - /data/docker/gitlab/config:/etc/gitlab
      - /data/docker/gitlab/logs:/var/log/gitlab
      - /data/docker/gitlab/data:/var/opt/gitlab
    networks:
      my-net:
        aliases:
          - gitlab-ce
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - gitlab-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/gitlab-runner:/etc/gitlab-runner
    networks:
      my-net:
        aliases:
          - gitlab-runner

networks:
  my-net:
    external: true
